/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiralabra;

import tiralabra.pathfinders.BFSPathfinder;
import java.io.IOException;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) throws IOException {
        var scenarios = ScenarioLoader.loadScenarios(Paths.get("C:\\Users\\FINDarkside\\Koulu\\Tiralabra\\ca_cave.map.scen"));
        BenchmarkRunner.runBencmark(scenarios);
    }

}
