/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiralabra;

import tiralabra.pathfinders.BFSPathfinder;
import java.io.IOException;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) throws IOException {
        //Map map = MapLoader.loadMap(Paths.get("C:\\Users\\FINDarkside\\Downloads\\AcrosstheCape.map\\AcrosstheCape.map"));
        //BFSPathfinder finder = new BFSPathfinder(map);

        
    }
}
